spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"          
            assertingparty:
              metadata-uri: https://dev-38785465.okta.com/app/exk6o68mv3qtbBIwU5d7/sso/saml/metadata
